#!/bin/bash

clear

cd src/boundaryConditions
./compile

cd ../mathematics
./compile

cd ../models
./compile

cd ../schemes
./compile

cd ../../applications/solvers/solidFoam
./compile

cd ../plasticFoam
./compile

cd ../../utilities/initialConditions
./compile